# Generated by Django 5.2.4 on 2025-07-11 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_location', models.CharField(max_length=255)),
                ('pickup_location', models.CharField(max_length=255)),
                ('dropoff_location', models.CharField(max_length=255)),
                ('cycle_used', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('route_data', models.JSONField()),
                ('log_data', models.JSONField()),
            ],
        ),
    ]
